on:
    workflow_dispatch:    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        - uses: TobKed/github-forks-sync-action@v0.2.0
          with:
            upstream_repository: gitkraken/vscode-gitlens
        
